#
# Makefile
#

LIBEXCIRCLESHOME = ../..

OBJS	= main.o kernel.o

LIBS	= $(LIBEXCIRCLESHOME)/lib/libexcircles.a \
		  $(CIRCLEHOME)/lib/libcircle.a

include $(LIBEXCIRCLESHOME)/Rules.mk

-include $(DEPS)
